"""Create lexical inverted index tables

Revision ID: 43eb5b2ea318
Revises: 3bbcbb212f93
Create Date: 2026-08-26 17:32:25.724435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43eb5b2ea318'
down_revision: Union[str, Sequence[str], None] = '3bbcbb212f93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lexical_terms',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('term', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('term')
    )
    op.create_table('lexical_postings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('term_id', sa.Integer(), nullable=False),
    sa.Column('chunk_id', sa.Integer(), nullable=False),
    sa.Column('term_frequency', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['chunks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['term_id'], ['lexical_terms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('term_id', 'chunk_id', name='uq_lexical_posting_term_chunk')
    )
    op.create_index(op.f('ix_lexical_postings_chunk_id'), 'lexical_postings', ['chunk_id'], unique=False)
    op.create_index(op.f('ix_lexical_postings_term_id'), 'lexical_postings', ['term_id'], unique=False)
    op.add_column('chunks', sa.Column('token_count', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chunks', 'token_count')
    op.drop_index(op.f('ix_lexical_postings_term_id'), table_name='lexical_postings')
    op.drop_index(op.f('ix_lexical_postings_chunk_id'), table_name='lexical_postings')
    op.drop_table('lexical_postings')
    op.drop_table('lexical_terms')
    # ### end Alembic commands ###
